language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

sudo: required

cache: pip

before_install:
  - python -m pip install --upgrade pip
  - pip install --upgrade setuptools

install:
  - pip install -r requirements.txt

script:
  - python magic_command_line.py --validate